### ISSUE TITLE
add a Polyline in node,show not a line but a point

### ISSUE THREAD

**Issue by scolar** [viromedia/virocore#123]
List<Vector> vectors = new ArrayList<>();
        // 0
        vectors.add(new Vector(boundingBox.minX, boundingBox.minY, boundingBox.minZ));
        // 1
        vectors.add(new Vector(boundingBox.minX, boundingBox.minY, boundingBox.maxZ));
        Polyline polyline = new Polyline(vectors, 0.006f);
       Node spawnNode = new Node();
        spawnNode.setGeometry(polyline);

**Comment by dthian** [comment]
Hey @scolar, the above is the correct way to construct and set a poly line geometry on a given node. If you don't see a line, it may be because the boundingBox values are returning 0 - they are not yet ready to be read as nothing yet has been rendered. You can try waiting a few milliseconds before requesting for such information, thereby giving the renderer time to load up the geometry:
```
new Handler(Looper.getMainLooper()).postDelayed(new Runnable() {
            @Override
            public void run() {
                BoundingBox bb = boxNode.getBoundingBox();
                Log.e("Test", "BoundingBox : " + bb.minX + " , " + bb.maxX);

            }
        }, 500);
```
