### ISSUE TITLE
when the groupNode getRotationEulerRealtime() changed,the childNode getRotationEulerRealtime() not change?

### ISSUE THREAD

**Issue by scolar** [viromedia/virocore#125]
mGroupNode.setGestureRotateListener(new GestureRotateListener() {
                        @Override
                        public void onRotate(int source, Node node, float radians, RotateState rotateState) {
                            if (rotateState == RotateState.ROTATE_END) {

                            } else {
                                Vector lastRotate = node.getRotationEulerRealtime();
                                Vector rotateTo = new Vector(lastRotate.x, lastRotate.y + radians, lastRotate.z);
                                mGroupNode.setRotation(rotateTo);
                                for (int i = 0; i < mGroupNode.getChildNodes().size(); i++) {
                                    Node node1 = mGroupNode.getChildNodes().get(i);
                                    Vector euler = node1.getRotationEulerRealtime();
                                    Log.i("euler" + i, "" + euler.y);
                                  }

**Comment by radvani** [comment]
Hi @scolar,

It looks like you're trying to get *global* rotation of the child node. The getRotationEulerRealtime() just returns the local rotation. To get the global rotation, you would do something like below. First, assume the scene is set up like this:

```
Node parent = new Node();
Node child = new Node();
parent.addChildNode(child);
```
Then, if we set the rotation of parent and child, you can then retrieve the local and global rotation like so:
```
parent.setRotation(new Vector(Math.toRadians(45), Math.toRadians(0), Math.toRadians(0)));
child.setRotation(new Vector(Math.toRadians(45), Math.toRadians(0), Math.toRadians(0)));

float localRotationX = childOne.getRotationEulerRealtime().x;
Matrix worldTransform = childOne.getWorldTransformRealTime();
Vector worldScale = worldTransform.extractScale();
Quaternion worldRotation = worldTransform.extractRotation(worldScale);
Vector worldEuler = worldRotation.toEuler();
```
In this example, Math.toDegrees(localRotationX) will be 45, and Math.toDegrees(worldEuler.x) will be 90.

*Important caveat*: in the current release, when you set the rotation of a Node via setRotation, that rotation isn't reflected in getRotationEulerRealtime() until the next frame (e.g. after a few milliseconds). This is fixed in the forthcoming release, which will be available next week.
