### ISSUE TITLE
Create 3d model Future

### ISSUE THREAD

**Issue by 544531645** [viromedia/virocore#149]
Have you considered being able to show 3D objects without a background from camera, like Scenekit, and load 3D model anywhere on the screen

**Comment by dam00n** [comment]
Yes, we have Viro3DSceneNavigator which allows the creation of 3D environments without AR or VR -> https://docs.viromedia.com/docs/viro3dscenenavigator

**Comment by VikAdvani** [comment]
Hi @544531645, this is possible with a ViroViewScene view in ViroCore. Using  ViroViewScene as your ViroView will support the the use case involving loading a 3D model  anywhere on the screen.

**Comment by 544531645** [comment]
@VikAdvani can you give me a demo code ?

**Comment by 544531645** [comment]
？？？？

**Comment by dthian** [comment]
Hey @544531645, as has mentioned above, you can use a [ViroViewScene](https://developer.viromedia.com/virocore/reference/com/viro/core/ViroViewScene.html) (scene with no camera, like SceneKit) to place objects anywhere on the screen. 

**Note** that you can only use any of these[ main views](https://virocore.viromedia.com/docs/views) (ViroViewScene / ViroViewGVR / etc) each one at a time, but not simultaneously in parallel. 

Creating a 3Dmodel in the center a ViroViewScene is pretty much the same as what you have [done before](https://github.com/viromedia/virocore/issues/142) in a ViroViewGVR scene - you should have already provided to you all the [documentation](https://virocore.viromedia.com/docs/3d-objects) and guides to be able to add a model to the scene using the same code. Even the hello world example code itself in the [getting started page](https://virocore.viromedia.com/docs/getting-started) should be sufficient. 

The only difference is that instead of a ViroViewGVR, you use a [ViroViewScene](https://developer.viromedia.com/virocore/reference/com/viro/core/ViroViewScene.html) instead. Again, the Hello World example code should be enough to get you started in the right direction:

```
// Within onCreate()
mViroView = new ViroViewScene(this, new ViroViewScene.StartupListener() {
            @Override
            public void onSuccess() {
                // Start building your scene here! We provide a sample "Hello World" scene
                createHelloWorldScene();
            }

            @Override
            public void onFailure(ViroViewScene.StartupError error, String errorMessage) {
                // Fail as you wish!
            }
        });
setContentView(mViroView);
```

**Comment by 544531645** [comment]
@dthian  you don't understand me , I mean create 3d in the view , So whatever you do, the model is in the linearlayout, as a view, right

**Comment by 544531645** [comment]
then the demo is ViroViewARCore , not VrioView Scene

**Comment by dthian** [comment]
> I mean create 3d in the view , So whatever you do, the model is in the linearlayout,

As shown above, we are creating a ViroViewScene and simply setting it on the activity like any other android view. **Any of the main [ViroViews](https://virocore.viromedia.com/docs/views) extends from FrameLayouts, and as such you can treat them like any android views - you can put this into a [linear layout like any android view](https://stackoverflow.com/questions/4203506/how-to-add-a-textview-to-a-linearlayout-dynamically-in-android).** 

Caveats: 
1) Note that only one [ViroViews](https://virocore.viromedia.com/docs/views) can be displayed at a time! 
2) At this time, ViroViews will have to be created and added to the Android ViewGroup layouts dynamically. 

> then the demo is ViroViewARCore , not VrioViewScene

I'm not sure what you mean here, can you please explain a little more? The above links should be sufficient and provide you all the material you need to get started. 

Having said that, we haven't actually tested a non-full screen ViroViewScene experience, so do let us know if you have any problems with it when you are trying it out! Thanks!

**Comment by dthian** [comment]
Resolving due to inactivity and that the original question has been answered.
