### ISSUE TITLE
shadow broken pixel 

### ISSUE THREAD

**Issue by 544531645** [viromedia/virocore#152]
![image](https://user-images.githubusercontent.com/15622364/41656551-e99ea0ec-74c2-11e8-8efb-c07957fc85e7.png)

**Comment by VikAdvani** [comment]
Hi @544531645, to get higher resolution shadows you can try to increase the shadow map size on the light casting the shadow.

For instance if you have a spotlight you set the shadow map size like this:
```spotlight.setShadowMapSize(2048);```

The default value is 1024. The value you set has to be a power of 2. Keep in mind, the larger you make shadow map size the slower the performance.

**Comment by 544531645** [comment]
I change to 4096 . also shadow broken @VikAdvani

**Comment by radvani** [comment]
You can also improve the shadow aliasing by shrinking the shadow frustum. If you're using a spotlight, this means making the inner angle and outer angle as small as possible, and making the near and far frustum planes as close together as possible.

Also, a 4096 size shadow map is likely to not work because it's too large.
