### ISSUE TITLE
while loading 10+ obj models at the same time, the app crashed?

### ISSUE THREAD

**Issue by scolar** [viromedia/virocore#169]
crash log as follow:
Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 9100 (pool-16-thread-), pid 8310
E/native: camera_image_stream.cc:114 Failed to extract the metadata or correct the timestamp, status=generic::deadline_exceeded: Timed out waiting for metadata.
E/native: camera_image_stream.cc:114 Failed to extract the metadata or correct the timestamp, status=CameraStatusErrorSpaceClass::ACAMERA

**Comment by dthian** [comment]
Hey @scolar, apologies for the late reply, is it possible to:
1) grab the logs on the device when the screen goes black?
2) Provide us the model you are trying to load?

From the above, I suspect that it may be a memory issue where we may be loading numerous memory intensive models into the scene. Much thanks!

**Comment by dthian** [comment]
Thanks @scolar, can you also please send the logcat logs on your device before and during the crash? Also, what is the model of the device that you are using?

**Comment by dthian** [comment]
Hey @scolar, thanks for providing the 3D model above. After taking a look at it, it looks like the model may be the result output of a 3D model scanner, due to the heavy unoptimized mesh tessellation that it has - is this true? 

Another thing we noticed as well is that the texture that you are using on that 3D model is **huge (around 2K-4K) ** and extremely memory intensive. Thus loading 10+ of them results in a memory issue that then causes the app to crash (you should see memory warnings and errors in the adb logcat). This can be solved by decreasing the resolution / size of the image - this may be the easiest task you can do to optimize our model, in attempts to place 10+ heavy weight models in your scene. 

Hope that helps!

**Comment by scolar** [comment]
Hey @dthian ,my device is Xiaomi MIX 2S,and the log as follow:
[log.txt](https://github.com/viromedia/virocore/files/2234796/log.txt)

**Comment by dthian** [comment]
Hey @scolar, have you tried reducing the size of the texture to the recommended size as mentioned above - does the crash still occur then?

**Comment by scolar** [comment]
I tried reducing the size of the texture to 1024, it can load 20+ obj models in the scene,when load 30+ obj models,the crash still occur. And i find that the scenekit of IOS can load 200+ obj models.Is there a way to improving loading efficiency.

**Comment by dthian** [comment]
Hey @scolar, with regards to the sceneKit IOS comparison, it is actually **non-trivial** to do an apples to apples comparison (or in this case, the number of models loaded). This is because there are so many different factors, like OS (iOS vs Android), Device model hardware with different memory capabilities (Samsung vs iPhones), and the type of model that is being loaded (how large the meshes / vertex counts are). Thus, the above is **not a proper comparison of performance.**

Having said that, we do strive to optimize our renderer to give the best performance for our developers. 

As such **_we've identified several memory leaks and performance improvements that will be in our upcoming release (around next week)_**. With that, I was able to load up 60 + full resolution M076.obj models (in the link you provided), inserting them into the scene one at a time. We'll update this issue once that release has been deployed.

Thus, we do support loading a reasonable number of heavily tessellated and memory intensive 3D model objects into the scene, like the one you provided in the link above. This should cover a majority of the common AR/VR mobile application use cases.

**Comment by dthian** [comment]
Hey @scolar, we've fixed and added a few optimizations in ViroCore 1.9 - could you re-verify to see if loading 10+ models is still an issue for you?  Thanks!

**Comment by LiamLuUW** [comment]
Hi @dthian  I have a similar issue with my app loading too much objects. The device i am using is a Pixel2. I am loading about 15 objects with different textures. I have tried reduce texture to about 500kb, but the app still crash upon loading objects. Here is the screenshot of my log:
<img width="1249" alt="screen shot 2018-08-22 at 12 10 14 pm" src="https://user-images.githubusercontent.com/19391598/44476125-d8ab8700-a604-11e8-92cd-0a4c45f04800.png">

Is there any other reason might cause this issue? Thank you!

**Comment by LiamLuUW** [comment]
@dthian  Thank you for your reply. What i found is instead of using different texture on different node, if I use one texture the app works ok. I have attached the object and various texture here
[model.zip](https://github.com/viromedia/virocore/files/2316743/model.zip)

And here is how i am using them in the code:
<img width="994" alt="screen shot 2018-08-23 at 9 55 44 pm" src="https://user-images.githubusercontent.com/19391598/44560783-624f7780-a71f-11e8-8c87-23ff0ae27130.png">
