### ISSUE TITLE
[Question] Utilizing cameraTextureName to process image data

### ISSUE THREAD

**Issue by Alex-Lai** [viromedia/virocore#177]
Hi there! So I'm aware that you can grab the camera texture name (id) from the ViroView. However I have't been able to find a good answer as to how to utilise the id. What is the best way to get the id into Bitmap form so that I can process it? Thanks in advance.

**Comment by achuvm** [comment]
Hi @Alex-Lai,

Use this [TextureReader.java](https://github.com/google-ar/arcore-android-sdk/blob/master/samples/computervision_java/app/src/main/java/com/google/ar/core/examples/java/computervision/TextureReader.java) class provided by Google for grabbing the texture info.

That'll give you the data as a [TextureReaderImage.java](https://github.com/google-ar/arcore-android-sdk/blob/master/samples/computervision_java/app/src/main/java/com/google/ar/core/examples/java/computervision/TextureReaderImage.java) which is just a wrapper around a ByteBuffer.

You can then use this data as-is, or you could convert it into a BitMap (not advised since the ByteBuffer itself already contains the data in its raw form). Here's on example on [StackOverflow](https://stackoverflow.com/questions/38639436/how-to-convert-bytebuffer-into-image-in-android) regarding converting a ByteBuffer -> Bitmap.

Let us know if that works!

**Comment by radvani** [comment]
Hi @Alex-Lai, in our next release there will be a more efficient way to to do this by way of a listener interface which will give you the raw image data each frame for you to process.

**Comment by Alex-Lai** [comment]
Thanks @achuvm for the info, I'll give that a try. @radvani sounds promising, looks forward to giving it a try! Is there an estimate on the date of the next release?

**Comment by radvani** [comment]
Yes, this next release should be out early next week. I would recommend waiting for that for processing image data as the previous camera texture ID method is quite difficult to get working correctly.

**Comment by dam00n** [comment]
CameraImageListener added to latest release, ViroCore 1.9

Release notes and upgrade instructions here -> https://virocore.viromedia.com/docs/releases
