### ISSUE TITLE
Video crash upon start the app

### ISSUE THREAD

**Issue by LiamLuUW** [viromedia/virocore#186]
Hi, I am trying to render a quad with video on it but it keep crashes the app upon start. 
This is the code I have for video object

    ``   Node videoNode = new Node();
        Uri parse = Uri.parse("file:///android_asset/demo.MP4");
        VideoTexture videoTexture = new VideoTexture(mViroView.getViroContext(), parse);
        Material videoMaterial = new Material();
        videoMaterial.setDiffuseTexture(videoTexture);
        Quad videoSurface = new Quad(1f, 1f);
        videoSurface.setMaterials(Arrays.asList(videoMaterial));
        videoNode.setGeometry(videoSurface);
        videoNode.setPosition(new Vector(0.5f,0f,0f));``

And this is the error log i am getting:
<img width="1356" alt="screen shot 2018-08-09 at 12 13 31 pm" src="https://user-images.githubusercontent.com/19391598/43911603-e57b2aa8-9bcd-11e8-8402-e9054d0301d2.png">

Thank you!

**Comment by manbod** [comment]
Hi @LiamLuUW ,
Thanks for reaching out! This video crash results due to an outdated exoplayer version in the build.gradle file. Apologies, this slipped when we updated our exoplayer dependency earlier. If you open your `build.gradle` file; under dependencies you should see a `compile 'com.google.android.exoplayer:exoplayer:r2.2.0'`. Change it to `compile 'com.google.android.exoplayer:exoplayer:2.7.1'`. We have updated our sample apps, here's the [code change](https://github.com/viromedia/virocore/commit/2771996d5e0057d604ebe69baf1b425b0ba83b6e). And we are updating our helloworld code samples that you downloaded earlier for future.

Thanks!

**Comment by LiamLuUW** [comment]
Thank you for the reply. So the dependency issue is solved but I have one follow up question. While the video is running, I am calling `videoTexture.isPlaying()` but it always returns false. Any idea what did I miss? Thanks a lot!

**Comment by manbod** [comment]
Uh oh, legit bug! Thanks for catching and reporting this. We have filed a bug internally and this should be fixed in the next release. In the meantime, while not ideal, one workaround to get past this bug would be to rely on `!videoTexture.isPaused()` instead of `videoTexture.isPlaying()`. I just tested and can confirm `videoTexture.isPaused()` is working correctly.

**Comment by LiamLuUW** [comment]
No problem!. Thanks for the help!
