### ISSUE TITLE
Models Disappearing 

### ISSUE THREAD

**Issue by pekayatt** [viromedia/virocore#194]
I have a scene with a FBX model showing the Solar System. It is just one FBX with all the planets and they are rotating.

Not sure why, but some of the planets disappear when the model is getting out of the camera view. Anyone had any similar problem?

I would like to not need to separate each of the planets, and still fearing that even after having they separated I still get the same problm.

Does VIROCORE make any kind of object occlusion?

Kind regards,

**Comment by dthian** [comment]
Hey @pekayatt, thanks for reaching out. As 3D objects in Viro are rendered back to front, they will be occluded in that manner. Whether an object is rendered in the scene is largely determine by it's axis aligned bounding box location in the world, and if the camera can 'see' that box. This bounding box is usually automatically determined from the 3D object that is provided, so I'm wondering if there's a potential issue there.

Could you provide us the the FBX and VRX model of your solar system, with it's textures, so that we can test and verify the issue?

Much thanks!

**Comment by dthian** [comment]
Closing due to months of inactivity.
