### ISSUE TITLE
ViroViewScene question

### ISSUE THREAD

**Issue by 544531645** [viromedia/virocore#209]
- [x] Review the documentation: https://virocore.viromedia.com/
  - [x] Search for existing issues: https://github.com/viromedia/virocore/issues
  - [x] Use the latest ViroCore release: https://virocore.viromedia.com/docs/releases
  - [x] Turn off Instant Run in Android Studio

## Environment
Please provide the following information about your environment:
Development OS: Windows
Device OS & Version: Android 8.0
Device(s): Google Pixel

## Description
https://developer.viromedia.com/virocore/reference/com/viro/core/ViroViewScene.html
    Animation animation = object.getAnimation("Take 001");
                animation.setLoop(true);
                animation.play();
animation only one time , not loop . Sometimes it's repeated several times,then also auto stop animation

**Comment by dthian** [comment]
Thanks @544531645, could you send us the 3D model with the animation so we can verify the bug on our end?

**Comment by 544531645** [comment]
@dthian send email to support email

**Comment by dthian** [comment]
Hey @544531645, as mentioned in the [documentation](https://developer.viromedia.com/virocore/reference/com/viro/core/Node.html), the Animation that is returned by the Node.java class is **new and not cached.** Thus you'll need to keep a reference to the animation in order to keep it alive. 

As such, if you do not keep a reference to the animation, like as you have done so above, the Java garbage collector can unpredictably clean the object up, thereby stopping your animation resulting in the bug that you see. I've verified this behavior by purposefully not keeping a strong reference, and forcing a GC - i see the bug occurring.

One way fix is to save a copy of the animation as a private member in the class of which you are playing this animation. Let me know if you have any difficulties with this.
