### ISSUE TITLE
Is it possible to do an animation with sequence of images in fbx model?

### ISSUE THREAD

**Issue by Ximmgon** [viromedia/virocore#235]
- [x] Review the documentation: https://virocore.viromedia.com/
  - [x] Search for existing issues: https://github.com/viromedia/virocore/issues
  - [x] Use the latest ViroCore release: https://virocore.viromedia.com/docs/releases
  - [x] Turn off Instant Run in Android Studio

## Description
I have an image and I want to do the "water" efect with that, the animator says that it is a sequence of images with that image, just says me that I have to change the texture, but I don't know if it is possible to do that on fbx model... Because when I try to add a "texture" the geometry of model is null... So I can't change the materials...

**Comment by dthian** [comment]
Hey @Ximmgon, thanks for reaching out. It should be possible within ViroCore to swap out a texture of a 3D model dynamically. Your approach is correct in the above - starting from the root node of your model, you would have to iterate through down its tree of subnodes, until you find a node with the material name that you are targeting to change. You can then simply swap out the texture within that material.

>Because when I try to add a "texture" the geometry of model is null... So I can't change the materials
 If you see the model in your scene, your nodes should have geometry - are you sure you are examining / iterating through the entire node tree to check for geometry?

**Comment by dthian** [comment]
> So I have to do a GIF? with my respective image?...

Well, since you've mentioned your texture is effectively "sequence of images with that image" - you could use a GIF texture that contains your image sequences. Another way is to apply each individual image yourself. 

> Yess! I have a node that contains an Object3D (The fbx model in vrx format),and other nodes with its respective Object3D, if I use the node.getGeometry() method it returns null, and if I check the object3D.getGeometry() that is inside the node, it returns null too.

I'm not sure if you fully understand the API - getGeometry() **only returns the geometry associated with that node.** As such calling object3D.getGeometry() returns the geometry associated with that object3D root node - and in certain 3d models, the geometry may not be at the root.

Thus, as mentioned previously, you will have to **iterate through the subtree of the 3d model, starting at the root of the 3d model, and check every node for geometry - have you done this yet, for _all_ the nodes within the 3d model?**

**Comment by Ximmgon** [comment]
> you will have to iterate through the subtree of the 3d model, starting at the root of the 3d model, and check every node for geometry - have you done this yet, for all the nodes within the 3d model?

And How I do that? Because if I want to iterate through the subtree of the 3d model, I suppose that I've to use object3D.getChildNodes() to obtain all nodes of 3d model ?, but it returns an empty list... so I cannot iterate through an empty list... Or I don't know how to do that...

**Comment by Ximmgon** [comment]
> on the callback?

I don't know why was not working, I had a flag that changes on callback, and when it turns true, it call a method which call "getChildNodes()" and returns an empty list, (probably a mistake that I can't see yet), but if I call the getChildNodes() on the callback as you said it works! Thank you.
