### ISSUE TITLE
RENDERING ISSUE

### ISSUE THREAD

**Issue by Ximmgon** [viromedia/virocore#257]
- [- ] Review the documentation: https://virocore.viromedia.com/
  - [- ] Search for existing issues: https://github.com/viromedia/virocore/issues
  - [- ] Use the latest ViroCore release: https://virocore.viromedia.com/docs/releases
  - [- ] Turn off Instant Run in Android Studio

## Description
Hello! I cannot render my vrx model, and my app says me that it has not errors while loading and adding into a scene. I even add lights and prove the same conditions with another vrx model and it rendered. I don't know what could be the problem. Here's my model and all the textures it uses.
[Finales2.zip](https://github.com/viromedia/virocore/files/2869924/Finales2.zip)

**Comment by Ximmgon** [comment]
I tried to add the scene the bounding box and it rendered it, but the model doesn't appear. I don't know if is a problem with my "model" or with viro.

**Comment by dam00n** [comment]
Hi @Ximmgon, we have been trying to get your model to work but it is not showing up except for the flag. It appears to be an issue with your model though we are not sure exactly what the problem is as we have not encountered this issue before. Here are some assets we provide that you can try, perhaps modeling them similarly would help -> https://docs.viromedia.com/docs/assets

**Comment by Ximmgon** [comment]
Thank to you, you did notice, it was because the modeling, and it was that, you have to separate your objects of their bones! 
"Usually objects are not a part of the skeleton tree and kept separate." 
Thanks!!
