### ISSUE TITLE
Simulate a visible light

### ISSUE THREAD

**Issue by jacobwyn** [viromedia/virocore#26]
Hi guys, I'm trying to simulate a visible light like this one
![1519116663076](https://user-images.githubusercontent.com/15327844/36414777-1b95d976-162c-11e8-9d56-e48b3f242e41.png)
Does your framework able to do such effect? 
Any help or idea will be appreciated !

**Comment by radvani** [comment]
Hi Jacob,

The best way to do this would be to apply a Spotlight
<https://developer.viromedia.com/virocore/reference/com/viro/core/Spotlight.html>,
and position it near where the light is on the car. That would give the
"cone of light" effect you're looking for. In order to get the "glow" like
effect, I would experiment with bloom
<https://developer.viromedia.com/virocore/reference/com/viro/core/Material.html#setBloomThreshold(float)>
--
try adding a bloom threshold to the material associated with the light, if
possible.

We're also working on emissive textures, for a future release, that will
help as well.

**Comment by radvani** [comment]
Hi Jacob,

The best way to do this would be to apply a [Spotlight](https://developer.viromedia.com/virocore/reference/com/viro/core/Spotlight.html), and position it near where the light is on the car. That would give the "cone of light" effect you're looking for. In order to get the glow-like effect, I would experiment with [bloom](https://developer.viromedia.com/virocore/reference/com/viro/core/Material.html#setBloomThreshold(float)) -- try adding a bloom threshold to the material associated with the light, if possible.

We're also working on emissive textures, for a future release, that will help as well.

**Comment by jacobwyn** [comment]
Hi @radvani, thanks for advice, I managed to do this 
![shyness](https://user-images.githubusercontent.com/15327844/36668486-297795ac-1afa-11e8-9f07-b06ec54aab68.png)
But bloom effect here is not so strong as I would like to have. 
Is any idea how can I increase this effect ?

```
     AmbientLight ambientLight = new AmbientLight();
        ambientLight.setIntensity(200);
        mArScene.getRootNode().addLight(ambientLight);

        Vector position = new Vector(0, 0, -1);
        Spotlight spotlight = new Spotlight();
        spotlight.setPosition(new Vector(0, 0, 0));
        spotlight.setDirection(position);
        spotlight.setIntensity(1000);
        spotlight.setColor(Color.WHITE);
        spotlight.setAttenuationStartDistance(2);
        spotlight.setAttenuationEndDistance(10);
        spotlight.setInnerAngle(15);
        spotlight.setOuterAngle(45);
        mArScene.getRootNode().addLight(spotlight);

        Box box = new Box(0.3f, 0.3f, 0.3f);
        Material material = new Material();
        Bitmap bitmap = Helper.getBitmapFromAsset(ViroARActivity.this, "andy.png");
        Texture texture = new Texture(bitmap, Texture.Format.RGBA8, true, true);
        material.setSpecularTexture(texture);
        material.setBloomThreshold(0.9f);
        material.setLightingModel(Material.LightingModel.PHONG);
        box.setMaterials(Arrays.asList(material));
        Node node = new Node();
        node.setGeometry(box);
        node.setPosition(position);
        mArScene.getRootNode().addChildNode(node);
```
Have played with bloom threshold and light intensity - does not help

**Comment by radvani** [comment]
Hi @jacobwyn, unfortunately we don't yet have an API to change the intensity of the Bloom, but I've added a task to our backlog so we can investigate this. In the meantime, increasing the intensity of the Spotlight should help; you can try values larger than 1000.

Also, could you clarify what you mean by attenuating the node opacity? Do you mean, have the objects inside the Node slowly fade out as they move away from the center of the node? We don't have any API for this at the moment.

**Comment by jacobwyn** [comment]
> Also, could you clarify what you mean by attenuating the node opacity? Do you mean, have the objects inside the Node slowly fade out as they move away from the center of the node? We don't have any API for this at the moment.

Yes, exactly.

**Comment by radvani** [comment]
That's interesting; this is something that should be possible when we expose custom shader modifications, which is on our backlog for a future release.

**Comment by jacobwyn** [comment]
Thanks in advance!
