### ISSUE TITLE
Non-AR Scene in Fragment 

### ISSUE THREAD

**Issue by marcspraragen** [viromedia/virocore#305]
## Environment
(Windows 10, Android Studio 3.4.1 compiling SDK 28, ViroCore 1_14.
Testing on Samsung S8+)

## Description
I can set up an ARScene (in a ViroViewARCore) in a fragment of an Android activity, and it works fine. 

However, setting up a 3D Scene (in a ViroViewScene) in the same fragment is causing me a lot of difficulty. 

I'm trying to set up 3 cameras (front, top, side) to swap points of view and I can't test that in AR. The fragment doesn't appear to load correctly with the Scene (just a white screen no matter which camera I try to use).

I've also attached a debug screen shot that confused me. Why is PortalScene() called by Scene()??? Is this pertinent?

## Reproducible Demo
See code and screenshots below:

[code.txt](https://github.com/viromedia/virocore/files/3553470/code.txt)

![debug](https://user-images.githubusercontent.com/8846596/63902866-615bc080-c9d9-11e9-96c3-e84775e49acc.png)
![Screenshot_20190828-211521_AR Placing Objects](https://user-images.githubusercontent.com/8846596/63902867-615bc080-c9d9-11e9-88e5-ac27bd678ed4.jpg)

**Comment by marcspraragen** [comment]
FYI after working with helloworld sample my guess is that a non-AR scene does not display background if it is set in a view before the scene is populated (i.e., no dimensions?).  Can't find any further info but closing this issue as I got it to work.

**Comment by marcspraragen** [comment]
I'm still struggling with how a non-AR scene determines its own dimensions. 

Is its size based on the parent view size? On its own root node bounding box?*

Does the scene resize itself based on what's put in it? 

How can I manually get/set the dimensions?  
 
*In Android Studio, the bounding box size of scene root node at any time returns 0,0,0, which makes drawing scene boundary polylines difficult. Should I just load a big fake 3D cube object and call it the scene?

**Comment by dthian** [comment]
A non-AR 3d ViroViewScene actually inherits from Android's FrameLayout View. As such, like any other Android view, its dimensions up updated in Android's layout pass. Any changes to this view size should be reflected in the rendered viewport (or "window"). What issues are you seeing?

**Comment by marcspraragen** [comment]
Hi Daniel-- 

Thanks for checking into this. I'm still not sure if or how the 3D non-AR Scene dimensions relate to the size of the 2D View (ViroViewScene) that contains it*. 

What I'm trying to do is create a rather complex non-AR PortalScene that contains animated 3D objects. My problem is that it's difficult for me to find the scale and boundaries of the Scene in order to scale and position the objects relative to their context/background.

My questions:

Does a Scene have any default geometry other than an origin point? The 
"set background cube with color" seems to suggest it exists, but the function immediately dives into native code with no returning geometry, so it's impossible to be sure.

Should I give up on working with a Scene as a visual entity, and just add a giant hollow 3D object to its root node and use that as the visual "scene"? 

Best,
--Marc

PS ViroCore is excellent and so far I am able to do everything that my iOS app counterparts have done with ARKit.
--------------

*I did notice that ARScene's Hit Tests go between 2D and 3D, but the 3D measurement seems to use native code, estimated realtime camera position, etc.

**Comment by dthian** [comment]
Perhaps there is a mis-understanding here. The scene's background is rendered without any perspective calculations and thus doesn't have any "measurable" dimensions - it is as if the 360 background or background cube is rendered at an "infinite" distance away.

> To find the scale and boundaries of the Scene in order to scale and position the objects relative to their context/background.

I'm not sure if the above makes sense - when you say "context/background", do you actually mean viewport sizes (The rendered windowed view)? Such that if the ViroViewScene size changes, the viewport size then changes, and you will then scale and position the objects relative to this viewport size to keep them in view?

If so, you wouldn't want to examine the size of the 3D scene whenever the ViroViewScene dimensions changes, as they are **independent** of each other (a 1 m box will remain 1m irregardless of ViroViewScene dimension changes). Instead you would want to examine the size difference of the ViroViewScene view's dimensions itself.

Also, instead of scaling the whole world and everything within it, i think you would actually need to adjust the camera instead either the FOV parameters (so that the camera can "see" more/less), or the position of the camera (pulling it back reveals more of the scene). 

Doing either of the above should "reveal" more / less of the objects in the scene within the viewport. This is much simpler instead of modifying the scale / positions of every object in the world.

Hope that helps!

**Comment by marcspraragen** [comment]
Thanks, Daniel-- that does answer my question. If I want the animated objects to visually interact with the "scene" / environment, that "scene" should really be a 3DObject loaded into the ViroCore Scene. The viewport and cameras will take care of the rest, as you mentioned.
