### ISSUE TITLE
Officially a dead project?

### ISSUE THREAD

**Issue by jeveloper** [viromedia/virocore#334]
First of all, hope you are all healthy and well! Thank you for the Viromedia team and contributors!
But can someone shed a light if this is a dead project?

No distributions since October 2019.

Happy to pay a monthly fee for a library that is alive and well.

Thank you

**Comment by dthian** [comment]
Hey @jeveloper, unfortunately, as you mentioned there isn't much activity on this library at the moment. There's been some work done since Nov '19, and we've just put in an automatic pipeline build for ViroCore with GitActions. No additional roadmap bug fixes / features have been planned. 

As an alternative, I am personally offering contract services / paid support for ViroCore. If that is something that may be of interest to you, feel free to reach out to me via email. I would love to hear your use cases and see if I can help.
