### ISSUE TITLE
Camera resolution

### ISSUE THREAD

**Issue by 544531645** [viromedia/virocore#38]
Now what resolution do we support? I think the resolution is a little bit low right now?

**Comment by achuvm** [comment]
ViroCore uses whatever resolution images are given to us by ARCore. As you can see from this Github [issue](https://github.com/google-ar/arcore-android-sdk/issues/56), ARCore currently controls the resolution and other camera properties in order to maintain tracking.

If/when an API is added to adjust camera properties, we'll be sure to expose it through Viro too.

**Comment by enpinzolas** [comment]
Currently ARCore has an API to control the camera resolution both through their java and C APIs. After recovering all the possible configurations though [arsession_getsupportedcameraconfigs](https://developers.google.com/ar/reference/c/group/session#arsession_getsupportedcameraconfigs), the resolution can be modified through [arsession_setcameraconfig](https://developers.google.com/ar/reference/c/group/session#arsession_setcameraconfig). It might be important to note that the documentation states the following:
> Starting in ARCore 1.12, changing the active camera config may cause the tracking state on certain devices to become permanently PAUSED. For consistent behavior across all supported devices, release any previously created anchors and trackables when setting a new camera config.

Should I open a new Issue about it?
