### ISSUE TITLE
ViroViewAR rotation everytime we re-enter AR

### ISSUE THREAD

**Issue by 544531645** [viromedia/virocore#40]
What happens when the camera occasionally turns sideways and then goes back to the vertical?

**Comment by dthian** [comment]
Hey @544531645, this is probably happening when you tilt/rotate your android device far enough, such that the activity orientation switches between landscape and portrait. With Android, you should be able to lock this behavior into portrait or landscape mode.

**Comment by 544531645** [comment]
I use demo ,aleardy set screenOrientation,="portrait", but it also happend

**Comment by 544531645** [comment]
phone : google pixel XL

**Comment by 544531645** [comment]
I find when go to background and back to app always happend

**Comment by dthian** [comment]
Hi @544531645, I've attempted to reproduce the issue with the enforced screenOrientation=portrait mode flag, and have attached a video gif here. In it you can see the activity momentarily rotate from portrait to landscape upon returning into the activity - is this the bug you are seeing?

![ezgif-4-1dacb2cc44](https://user-images.githubusercontent.com/1904934/37302825-d9c6ab88-25e9-11e8-98e2-0a92e849ef83.gif)

This appears to be a bug on the ViroCore platform, I've filed a bug so that we may be able to patch it. This issue will be updated once the fix has been pushed into release.

**Comment by 544531645** [comment]
yes ，This is my bug.

**Comment by 544531645** [comment]
This problem occurs when I suddenly pick up my phone from the table.

**Comment by dam00n** [comment]
This issue has been fixed in the latest update, ViroCore 1.5. Release notes and upgrade instructions here -> https://virocore.viromedia.com/docs/releases

Let us know if you are still having issues after upgrading.
