### ISSUE TITLE
ARretail example take too much time to detect surface after update to  1.5.0

### ISSUE THREAD

**Issue by sw-tt-darshanmistry** [viromedia/virocore#67]
Hello,

ARRetail example works nicely before updating viro library to 1.5.0. When I updated virocore library to 1.5.0 it takes too much time to detect surface. I have also re-download ARRetail from GitHub but the same issue persists.

**Comment by dthian** [comment]
Hi @sw-tt-darshanmistry, thanks for reaching out. Unfortunately, I can't seem to reproduce this issue and am able to detect a surface and have the cursor show pretty quickly upon the start of the ar activity.

How were you able to empirically come to your conclusion above? 
For your before-after-1.5-comparison, can you please confirm that:
1 - You are performing the before-after tests with the same surface? (Comparing with different surfaces is like comparing apples and oranges and will yield different results)
2 - You are performing the tests on a nearby surface? (ARCore / mobile depth sensing does not work as well with great distances). 

If (1) and (2) above are true, then can you please provide a video of viro_1.5 and before viro_1.5 so that we can visually do a side by side comparison? (EZ Screen Recorder is a useful screen record app if you need one). It might just be that ARCore itself does not handle well with certain types of surfaces specific to your current situation.

**Comment by dam00n** [comment]
Closing issue as no repro. Please reopen if you are still seeing the issue with the information requested.
