### ISSUE TITLE
[Feature Request] Fallback to 3DOF AR

### ISSUE THREAD

**Issue by pixoglcresce** [viromedia/virocore#81]
Hello ViroCore team! 
I'm not 100% sure if this actually really is a feature request or if it's somehow already achievable using the existing APIs, but I couldn't find any specific reference in documentation/code samples.

Given the (for now) quite limited support for ARCore among Android devices, would it be possible to fallback to a gyroscope based AR solution, when 6DOF are not supported? I'm talking about displaying some 3D object somewhere in the AR scene with a background from the camera feed and update only the in-scene camera rotations accordingly with the device ones. 
Moving in space wouldn't affect the camera position of course but the 3D rendering would "stay in place" coherently with its starting position when the user inspects the surroundings.

Again, apologies if this is already somehow achievable (I only found references to 3DOF when talking about G/OVR Views), I'm still new to the SDK.

Thanks!

**Comment by radvani** [comment]
Hi @pixoglcresce, thanks for checking out Viro. We don't have any plans to add a 3DOF mode, mainly because:

1. The things you're able to do in 3DOF are limited, and the gap between what an AR capable device can do vs. what an incapable device can do is only going to increase rapidly in the near-term. Because of this, a 3DOF fallback would become less and less useful over time.

2. We use ARCore for our underlying AR implementation, and currently Google doesn't support a 3DOF mode. However, if Google were to offer a fallback 3DOF mode in ARCore, we would consider adding this functionality as well.

**Comment by pixoglcresce** [comment]
Thanks for the quick and insightful reply!
