### ISSUE TITLE
Support to render object dimensions for 3D components natively

### ISSUE THREAD

**Issue by manikantagarikipati** [viromedia/virocore#83]
Providing support to display object dimensions for 3D components would be a great feature to have.

**Comment by dthian** [comment]
Thanks @manikantagarikipati for filing this feature request. When you mentioned "object dimensions for 3D components", did you mean the dimensions of a bounding box that has been created for a 3D component?

**Comment by manikantagarikipati** [comment]
Hi @dthian , 

Yes i mean by the representation of dimensions of the bounding box which gets created for a 3DObject, Just like the screen shot below.

<img width="400" alt="screen shot 2018-04-18 at 10 08 32 am" src="https://user-images.githubusercontent.com/7972131/38912029-ae909d1a-42f0-11e8-83d3-1c2191f64954.png">

**Comment by manikantagarikipati** [comment]
@dthian is there any way to achieve the above functionality ( displaying the dimensions) in the current version of virocore_1.1.0 ?

**Comment by dthian** [comment]
Get @manikantagarikipati, apologies for the delay. Yup it should be possible, you can either:
1 - Use another 3D object (a transparent cube with lines) that you can then place at the position of your 3d furniture, and re-use it for all your 3D furnitures (simply scale them). Because you know both the position and the scale, you can then place the numeric text dimensions on the sides. To get the size of the bounding box, you can use getBoundingBox() in [Node](https://developer.viromedia.com/virocore/reference/com/viro/core/Node.html).

2- Similar to (1), but instead of a 3D object, you can also use the [Polyline](https://developer.viromedia.com/virocore/reference/com/viro/core/Polyline.html) API to draw the lines of a box. 

Hope that helps!
