### ISSUE TITLE
[Question] ARRetail Set Scale product object not working?

### ISSUE THREAD

**Issue by tuzenvn** [viromedia/virocore#88]
I using setScale method like below code but model display does not change size.

**productModel.loadModel(Uri.parse("file:///android_asset/DNTQ.obj"), Object3D.Type.OBJ, new AsyncObject3DListener() {
            @Override
            public void onObject3DLoaded(final Object3D object3D, Object3D.Type type) {
                object3D.setLightReceivingBitMask(1);
                mProductModelGroup = object3D;

                Log.d(" ============= SCALE", " x :  " + productModel.getScaleRealtime().x + "   y:  " + productModel.getScaleRealtime().y + "   z:  " + productModel.getScaleRealtime().z);

                object3D.setScale(new Vector(0.00175, 0.00175, 0.00175));
                mProductModelGroup.setOpacity(0);
                mLastProductRotation = object3D.getRotationEulerRealtime();
                productModel.setScale(new Vector(0.00175, 0.00175, 0.00175));

                Log.d("-------------- SCALE", " x :  " + productModel.getScaleRealtime().x + "   y:  " + productModel.getScaleRealtime().y + "   z:  " + productModel.getScaleRealtime().z);
            }

            @Override
            public void onObject3DFailed(String error) {
                Log.e("Viro", " Model load failed : " + error);
            }
        });**

The values from Logcat of: 
============= SCALE VL:  x :  1.0   y:  1.0   z:  1.0
-------------- SCALE VL:  x :  1.0   y:  1.0   z:  1.0

Can you help me solve it?

**Comment by manbod** [comment]
Hey @tuzenvn ,
In your code, I am not sure what you are doing by `mProductModelGroup = object3D;` Did you also change this line at the bottom of the `init3DModelProduct` method? --> `mProductModelGroup.addChildNode(productModel);` 
Irrespective of that, I tested the ARRetail sample by modifying the code as below, and can confirm scaling should work correctly.
```java
 // Load the model from the given mSelected Product
        final Object3D productModel = new Object3D();
        productModel.loadModel(Uri.parse(mSelectedProduct.m3DModelUri), Object3D.Type.FBX, new AsyncObject3DListener() {
            @Override
            public void onObject3DLoaded(Object3D object3D, Object3D.Type type) {
                object3D.setLightReceivingBitMask(1);
                object3D.setScale(new Vector(0.2, 0.2, 0.2));
                mProductModelGroup.setOpacity(0);
                mProductModelGroup.setScale(new Vector(0.9, 0.9, 0.9));
                Log.d("-------------- SCALE", " x :  " + object3D.getScaleRealtime().x + "   y:  " + object3D.getScaleRealtime().y + "   z:  " + object3D.getScaleRealtime().z);
                mLastProductRotation = object3D.getRotationEulerRealtime();
            }

            @Override
            public void onObject3DFailed(String error) {
                Log.e("Viro"," Model load failed : " + error);
            }
        });
```
I just added `object3D.setScale(new Vector(0.2, 0.2, 0.2));` and the log statement above in the given sample code. And it sets the scale correctly at (0.2,0.2,0.2). From our documentation on `getScaleRealtime()` [here](https://developer.viromedia.com/virocore/reference/com/viro/core/Node.html#getScaleRealtime()), note that this may not match the value last set by setScale(Vector) because there may be an ongoing animation. Which means that since the setScale animation (changing the scale) happens on the rendering thread, it may take some while for the values returned by `getScaleRealtime` to return the correct scale. I verified the above by logging scale values in `productModel`'s `onClick()` method as below, and I could see the values changing correctly
```java
        // Set click listeners on this 3D product
        productModel.setClickListener(new ClickListener() {
            @Override
            public void onClick(int i, Node node, Vector vector) {
                float x = productModel.getScaleRealtime().x;
                float y = productModel.getScaleRealtime().y;
                float z = productModel.getScaleRealtime().z;
                productModel.setScale(new Vector(x-0.1, y-0.1, z-0.1));
                Log.d("-------------- SCALE", " x :  " + productModel.getScaleRealtime().x + "   y:  " + productModel.getScaleRealtime().y + "   z:  " + productModel.getScaleRealtime().z);


            }

            @Override
            public void onClickState(int i, Node node, ClickState clickState, Vector vector) {
                onModelClick(clickState);
            }
        });
```

**Comment by tuzenvn** [comment]
thanks alot I done it!
